/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Working2RouteImport } from './routes/working-2'
import { Route as Working1RouteImport } from './routes/working-1'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiShapesTableServerRouteImport } from './routes/api/shapes.$table'

const rootServerRouteImport = createServerRootRoute()

const Working2Route = Working2RouteImport.update({
  id: '/working-2',
  path: '/working-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Working1Route = Working1RouteImport.update({
  id: '/working-1',
  path: '/working-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesTableServerRoute = ApiShapesTableServerRouteImport.update({
  id: '/api/shapes/$table',
  path: '/api/shapes/$table',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/working-1': typeof Working1Route
  '/working-2': typeof Working2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/working-1': typeof Working1Route
  '/working-2': typeof Working2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/working-1': typeof Working1Route
  '/working-2': typeof Working2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/working-1' | '/working-2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/working-1' | '/working-2'
  id: '__root__' | '/' | '/working-1' | '/working-2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Working1Route: typeof Working1Route
  Working2Route: typeof Working2Route
}
export interface FileServerRoutesByFullPath {
  '/api/shapes/$table': typeof ApiShapesTableServerRoute
}
export interface FileServerRoutesByTo {
  '/api/shapes/$table': typeof ApiShapesTableServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/shapes/$table': typeof ApiShapesTableServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/shapes/$table'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/shapes/$table'
  id: '__root__' | '/api/shapes/$table'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiShapesTableServerRoute: typeof ApiShapesTableServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/working-2': {
      id: '/working-2'
      path: '/working-2'
      fullPath: '/working-2'
      preLoaderRoute: typeof Working2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/working-1': {
      id: '/working-1'
      path: '/working-1'
      fullPath: '/working-1'
      preLoaderRoute: typeof Working1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/shapes/$table': {
      id: '/api/shapes/$table'
      path: '/api/shapes/$table'
      fullPath: '/api/shapes/$table'
      preLoaderRoute: typeof ApiShapesTableServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Working1Route: Working1Route,
  Working2Route: Working2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiShapesTableServerRoute: ApiShapesTableServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
